server.port=8081
spring.application.name=user-service
app.security.enabled=true

# TEST-DEV KONFIGURACJA
spring.datasource.url=jdbc:postgresql://postgres:5432/user_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true
spring.flyway.clean-on-validation-error=false

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true

logging.level.root=INFO
logging.level.pl.dmcs.userservice=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8060/realms/boat-delivery-realm/protocol/openid-connect/certs

# Webhook
app.webhook.keycloak-secret=c8d904f5-5322-4d56-affb-fe63b9c436fb

# Synchronizacja - TEST-DEV
app.sync.enabled=true
app.sync.environment=test-dev
app.sync.migrate-on-startup=true
app.sync.default-password=password123
app.sync.keycloak-admin-url=http://keycloak:8060
app.sync.keycloak-admin-username=admin
app.sync.keycloak-admin-password=admin
app.sync.keycloak-realm=boat-delivery-realm
app.sync.keycloak-client-id=admin-cli
app.sync.audit-conflicts=true

