quarkus.application.name=order-service
quarkus.http.port=8081
quarkus.eureka.prefer-same-zone=true
quarkus.eureka.service-url.default=http://localhost:8761/eureka
quarkus.eureka.metadata.app-key=order-service
quarkus.eureka.heartbeat.enabled=true
quarkus.eureka.heartbeat.health-path=/info/health
quarkus.eureka.heartbeat.status-path=/info/status