quarkus.application.name=order-service
quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/order_service_db
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

app.host.name=localhost
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

google.api.key=xddd
here.api.key=xddd

quarkus.rest-client.google-maps-api.url=https://maps.googleapis.com
quarkus.rest-client.here-geocode-api.url=https://geocode.search.hereapi.com