package p.lodz.pl.model.enums;

public enum OrderStatus {
    WAITING_FOR_PAYMENT,
    ORDER_CREATED,
    CALCULATING_ROUTE_RECEIVE,
    ROUTE_ASSIGNED_RECEIVE,
    IN_TRANSIT_FOR_PACKAGE,
    ORDER_RECEIVED_FROM_CUSTOMER,
    IN_SORTING_CENTER,
    CALCULATING_ROUTE_DELIVERY,
    ROUTE_ASSIGNED_DELIVERY,
    IN_TRANSIT_TO_CUSTOMER,
    DELIVERY_COMPLETED,
    ORDER_CANCELED
}