server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: kiladotestu@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    servlet:
      load-on-startup: 1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8060/realms/boat-delivery-realm/protocol/openid-connect/certs}

smsapi:
  token: ${SMSAPI_TOKEN}
  sender: Test # JUDASZE Z SMSAPI NIE POWALAJA ZMIENIC NAZWY BEZ AKTYWACJI KONTA FIRMOWEGO!!!!!!!!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/