server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedMethods: "*"
                allowedHeaders: "*"
          routes:
            # Routing do serwisu user-service
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/user/**, /api/transport/**

            # Routing do serwisu order-service
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka